### ISSUE TITLE
error when run `npm run build`

### ISSUE THREAD

**Issue by GodsDusk** [shibing624/ChatPilot#2]
[vite:load-fallback] Could not load /Users/Documents/GitHub/ChatPilot/web/src/lib/stores (imported by src/routes/+layout.svelte): ENOENT: no such file or directory, open '/Users/Documents/GitHub/ChatPilot/web/src/lib/stores'
error during build:
Error: Could not load /Users/Documents/GitHub/ChatPilot/web/src/lib/stores (imported by src/routes/+layout.svelte): ENOENT: no such file or directory, open '/Users/Documents/GitHub/ChatPilot/web/src/lib/stores'
    at async open (node:internal/fs/promises:633:25)
    at async Object.readFile (node:internal/fs/promises:1242:14)
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/Documents/GitHub/ChatPilot/web/node_modules/rollup/dist/es/shared/node-entry.js:25444:28)
    at async file:///Users/Documents/GitHub/ChatPilot/web/node_modules/rollup/dist/es/shared/node-entry.js:24611:75
    at async Queue.work (file:///Users/Documents/GitHub/ChatPilot/web/node_modules/rollup/dist/es/shared/node-entry.js:25654:32)

**Comment by shibing624** [comment]
fixed.
